import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const themesDir = resolve(root, "themes");

const sharedColors = (p) =>
  Object.fromEntries([
    ["focusBorder", p.accent],
    ["foreground", p.fg],
    ["disabledForeground", `${p.muted}99`],
    ["descriptionForeground", p.secondaryText],
    ["errorForeground", p.error],
    ["textLink.foreground", p.accent],
    ["textLink.activeForeground", p.accentStrong],
    ["textPreformat.foreground", p.string],
    ["textBlockQuote.background", p.surface],
    ["textBlockQuote.border", p.accent2],
    ["textCodeBlock.background", p.panel],
    ["textSeparator.foreground", p.border],
    ["selection.background", p.selection],
    ["icon.foreground", p.secondaryText],
    ["contrastActiveBorder", "#00000000"],
    ["contrastBorder", "#00000000"],
    ["sash.hoverBorder", p.accent],
    ["titleBar.activeBackground", p.chrome],
    ["titleBar.activeForeground", p.fg],
    ["titleBar.inactiveBackground", p.surface],
    ["titleBar.inactiveForeground", p.muted],
    ["titleBar.border", p.border],
    ["activityBar.background", p.surface],
    ["activityBar.foreground", p.fg],
    ["activityBar.inactiveForeground", p.muted],
    ["activityBar.activeBorder", p.accent],
    ["activityBar.activeBackground", p.panel],
    ["activityBarBadge.background", p.accent],
    ["activityBarBadge.foreground", p.badgeFg],
    ["sideBar.background", p.surface],
    ["sideBar.foreground", p.secondaryText],
    ["sideBar.border", p.border],
    ["sideBarTitle.foreground", p.fg],
    ["sideBarSectionHeader.background", p.panel],
    ["sideBarSectionHeader.foreground", p.fg],
    ["sideBarSectionHeader.border", p.border],
    ["sideBarStickyScroll.background", p.surface],
    ["sideBarStickyScroll.border", p.border],
    ["list.activeSelectionBackground", p.listActive],
    ["list.activeSelectionForeground", p.selectedFg],
    ["list.focusBackground", p.listFocus],
    ["list.focusForeground", p.selectedFg],
    ["list.hoverBackground", p.listHover],
    ["list.hoverForeground", p.fg],
    ["list.inactiveSelectionBackground", p.listInactive],
    ["list.inactiveSelectionForeground", p.fg],
    ["list.dropBackground", p.drop],
    ["list.highlightForeground", p.accent],
    ["list.invalidItemForeground", p.error],
    ["list.errorForeground", p.error],
    ["list.warningForeground", p.warning],
    ["listFilterWidget.background", p.panel],
    ["listFilterWidget.outline", p.border],
    ["listFilterWidget.noMatchesOutline", p.error],
    ["tree.indentGuidesStroke", p.border],
    ["tree.inactiveIndentGuidesStroke", p.subtleBorder],
    ["commandCenter.background", p.panel],
    ["commandCenter.foreground", p.fg],
    ["commandCenter.border", p.border],
    ["menu.background", p.panel],
    ["menu.foreground", p.fg],
    ["menu.selectionBackground", p.listActive],
    ["menu.selectionForeground", p.selectedFg],
    ["menu.selectionBorder", p.border],
    ["menu.separatorBackground", p.border],
    ["quickInput.background", p.panel],
    ["quickInput.foreground", p.fg],
    ["quickInputList.focusBackground", p.listActive],
    ["quickInputList.focusForeground", p.selectedFg],
    ["quickInputTitle.background", p.surface],
    ["quickInputTitle.foreground", p.fg],
    ["editorGroupHeader.tabsBackground", p.surface],
    ["editorGroupHeader.noTabsBackground", p.surface],
    ["editorGroupHeader.border", p.border],
    ["editorGroup.border", p.border],
    ["editorGroup.dropBackground", p.drop],
    ["tab.activeBackground", p.chrome],
    ["tab.activeForeground", p.fg],
    ["tab.activeBorderTop", p.accent],
    ["tab.activeBorder", p.border],
    ["tab.inactiveBackground", p.surface],
    ["tab.inactiveForeground", p.muted],
    ["tab.inactiveModifiedBorder", p.warning],
    ["tab.unfocusedActiveBackground", p.surface],
    ["tab.unfocusedActiveForeground", p.secondaryText],
    ["tab.unfocusedInactiveBackground", p.surface],
    ["tab.unfocusedInactiveForeground", p.muted],
    ["tab.border", p.border],
    ["tab.lastPinnedBorder", p.border],
    ["breadcrumb.background", p.chrome],
    ["breadcrumb.foreground", p.secondaryText],
    ["breadcrumb.focusForeground", p.fg],
    ["breadcrumb.activeSelectionForeground", p.accent],
    ["breadcrumbPicker.background", p.panel],
    ["editor.background", p.bg],
    ["editor.foreground", p.fg],
    ["editorLineNumber.foreground", p.lineNumber],
    ["editorLineNumber.activeForeground", p.secondaryText],
    ["editorCursor.foreground", p.cursor],
    ["editorCursor.background", p.cursorCharacterForeground],
    ["editor.selectionBackground", p.selection],
    ["editor.inactiveSelectionBackground", p.inactiveSelection],
    ["editor.selectionHighlightBackground", p.selectionHighlight],
    ["editor.selectionHighlightBorder", p.selectionBorder],
    ["editor.wordHighlightBackground", p.wordHighlight],
    ["editor.wordHighlightBorder", p.wordHighlightBorder],
    ["editor.wordHighlightStrongBackground", p.wordHighlightStrong],
    ["editor.wordHighlightStrongBorder", p.wordHighlightStrongBorder],
    ["editor.findMatchBackground", p.findMatch],
    ["editor.findMatchBorder", p.findMatchBorder],
    ["editor.findMatchHighlightBackground", p.findMatchHighlight],
    ["editor.findMatchHighlightBorder", p.findMatchBorder],
    ["editor.findRangeHighlightBackground", p.findRange],
    ["editor.findRangeHighlightBorder", p.findMatchBorder],
    ["editor.hoverHighlightBackground", p.lineHighlight],
    ["editor.lineHighlightBackground", p.lineHighlight],
    ["editor.lineHighlightBorder", p.subtleBorder],
    ["editor.rangeHighlightBackground", p.rangeHighlight],
    ["editor.rangeHighlightBorder", p.subtleBorder],
    ["editor.symbolHighlightBackground", p.rangeHighlight],
    ["editor.symbolHighlightBorder", p.selectionBorder],
    ["editorIndentGuide.background1", p.subtleBorder],
    ["editorIndentGuide.activeBackground1", p.border],
    ["editorWhitespace.foreground", `${p.border}99`],
    ["editorRuler.foreground", p.subtleBorder],
    ["editorBracketMatch.background", p.wordHighlight],
    ["editorBracketMatch.border", p.accent2],
    ["editorBracketHighlight.foreground1", p.accent],
    ["editorBracketHighlight.foreground2", p.accent2Bright],
    ["editorBracketHighlight.foreground3", p.secondaryText],
    ["editorBracketHighlight.foreground4", p.warning],
    ["editorBracketHighlight.foreground5", p.type],
    ["editorBracketHighlight.foreground6", p.bracketAlt],
    ["editorBracketHighlight.unexpectedBracket.foreground", p.error],
    ["editor.foldBackground", p.fold],
    ["editor.linkedEditingBackground", p.selectionHighlight],
    ["editorOverviewRuler.border", "#00000000"],
    ["editorOverviewRuler.findMatchForeground", p.findMatchBorder],
    ["editorOverviewRuler.rangeHighlightForeground", p.selectionBorder],
    ["editorOverviewRuler.selectionHighlightForeground", p.accent],
    ["editorOverviewRuler.wordHighlightForeground", p.accent2Bright],
    ["editorOverviewRuler.wordHighlightStrongForeground", p.accent],
    ["editorOverviewRuler.modifiedForeground", p.accent],
    ["editorOverviewRuler.addedForeground", p.accent2],
    ["editorOverviewRuler.deletedForeground", p.accentMuted],
    ["editorGutter.background", p.bg],
    ["editorGutter.modifiedBackground", p.accent],
    ["editorGutter.addedBackground", p.accent2],
    ["editorGutter.deletedBackground", p.accentMuted],
    ["editorGutter.foldingControlForeground", p.secondaryText],
    ["editorWidget.background", p.panel],
    ["editorWidget.border", p.border],
    ["editorSuggestWidget.background", p.panel],
    ["editorSuggestWidget.border", p.border],
    ["editorSuggestWidget.foreground", p.fg],
    ["editorSuggestWidget.highlightForeground", p.accent],
    ["editorSuggestWidget.selectedBackground", p.listActive],
    ["editorSuggestWidget.selectedForeground", p.selectedFg],
    ["editorHoverWidget.background", p.panel],
    ["editorHoverWidget.border", p.border],
    ["editorHoverWidget.foreground", p.fg],
    ["editorStickyScroll.background", p.chrome],
    ["editorStickyScroll.border", p.border],
    ["editorStickyScrollHover.background", p.lineHighlight],
    ["editorMarkerNavigation.background", p.panel],
    ["editorMarkerNavigationError.background", p.error],
    ["editorMarkerNavigationWarning.background", p.warning],
    ["editorMarkerNavigationInfo.background", p.info],
    ["editorError.foreground", p.error],
    ["editorError.border", `${p.error}00`],
    ["editorWarning.foreground", p.warning],
    ["editorWarning.border", `${p.warning}00`],
    ["editorInfo.foreground", p.info],
    ["editorInfo.border", `${p.info}00`],
    ["editorHint.foreground", p.accent2Bright],
    ["editorHint.border", `${p.accent2Bright}00`],
    ["editorCodeLens.foreground", p.muted],
    ["editorLightBulb.foreground", p.warning],
    ["editorLightBulbAutoFix.foreground", p.accent2Bright],
    ["editorInlayHint.background", p.inlayBg],
    ["editorInlayHint.foreground", p.inlayFg],
    ["editorInlayHint.typeBackground", p.inlayTypeBg],
    ["editorInlayHint.typeForeground", p.inlayTypeFg],
    ["editorInlayHint.parameterBackground", p.inlayParamBg],
    ["editorInlayHint.parameterForeground", p.inlayParamFg],
    ["peekView.border", p.border],
    ["peekViewEditor.background", p.bg],
    ["peekViewEditor.matchHighlightBackground", p.findMatchHighlight],
    ["peekViewResult.background", p.panel],
    ["peekViewResult.fileForeground", p.fg],
    ["peekViewResult.lineForeground", p.secondaryText],
    ["peekViewResult.matchHighlightBackground", p.findMatchHighlight],
    ["peekViewResult.selectionForeground", p.selectedFg],
    ["peekViewResult.selectionBackground", p.listActive],
    ["peekViewTitle.background", p.surface],
    ["peekViewTitleDescription.foreground", p.secondaryText],
    ["panel.background", p.panelBg],
    ["panel.border", p.border],
    ["panelTitle.activeBorder", p.accent],
    ["panelTitle.activeForeground", p.fg],
    ["panelTitle.inactiveForeground", p.secondaryText],
    ["panelInput.border", p.border],
    ["panelSection.border", p.border],
    ["panelSectionHeader.background", p.surface],
    ["panelSectionHeader.foreground", p.fg],
    ["panelStickyScroll.background", p.chrome],
    ["panelStickyScroll.border", p.border],
    ["statusBar.background", p.surface],
    ["statusBar.foreground", p.fg],
    ["statusBar.border", p.border],
    ["statusBar.debuggingBackground", p.accent],
    ["statusBar.debuggingForeground", p.badgeFg],
    ["statusBar.noFolderBackground", p.surface],
    ["statusBarItem.hoverBackground", p.listHover],
    ["statusBarItem.prominentBackground", p.listActive],
    ["statusBarItem.prominentHoverBackground", p.listFocus],
    ["statusBarItem.remoteBackground", p.accent2Fill],
    ["statusBarItem.remoteForeground", p.badgeLight],
    ["statusBarItem.errorBackground", p.statusBarErrorBg],
    ["statusBarItem.errorForeground", p.errorFg],
    ["statusBarItem.warningBackground", p.warning],
    ["statusBarItem.warningForeground", p.buttonFg],
    ["button.background", p.buttonBg],
    ["button.foreground", p.buttonFg],
    ["button.hoverBackground", p.buttonHoverBg],
    ["button.border", "#00000000"],
    ["button.secondaryBackground", p.accent2Fill],
    ["button.secondaryForeground", p.badgeLight],
    ["button.secondaryHoverBackground", p.accent2FillHover],
    ["checkbox.background", p.panel],
    ["checkbox.foreground", p.fg],
    ["checkbox.border", p.border],
    ["input.background", p.panel],
    ["input.foreground", p.fg],
    ["input.border", p.border],
    ["input.placeholderForeground", p.muted],
    ["inputOption.activeBorder", p.accent],
    ["inputValidation.errorBackground", p.panel],
    ["inputValidation.errorBorder", p.error],
    ["inputValidation.infoBackground", p.panel],
    ["inputValidation.infoBorder", p.info],
    ["inputValidation.warningBackground", p.panel],
    ["inputValidation.warningBorder", p.warning],
    ["dropdown.background", p.panel],
    ["dropdown.foreground", p.fg],
    ["dropdown.border", p.border],
    ["badge.background", p.accent2Fill],
    ["badge.foreground", p.badgeLight],
    ["progressBar.background", p.accent],
    ["scrollbar.shadow", "#00000000"],
    ["scrollbarSlider.background", `${p.border}88`],
    ["scrollbarSlider.hoverBackground", `${p.border}BB`],
    ["scrollbarSlider.activeBackground", `${p.accent}88`],
    ["notifications.background", p.panel],
    ["notifications.border", p.border],
    ["notificationCenterHeader.background", p.surface],
    ["notificationCenterHeader.foreground", p.fg],
    ["notificationLink.foreground", p.accent],
    ["pickerGroup.foreground", p.accent2],
    ["pickerGroup.border", p.border],
    ["terminal.background", p.bg],
    ["terminal.foreground", p.fg],
    ["terminal.border", p.border],
    ["terminal.selectionBackground", p.selection],
    ["terminal.selectionForeground", p.selectedFg],
    ["terminalCursor.background", p.cursorCharacterForeground],
    ["terminalCursor.foreground", p.cursor],
    ["terminal.findMatchBackground", p.findMatch],
    ["terminal.findMatchBorder", p.findMatchBorder],
    ["terminal.ansiBlack", p.terminalAnsiBlack],
    ["terminal.ansiRed", p.terminalAnsiRed],
    ["terminal.ansiGreen", p.terminalAnsiGreen],
    ["terminal.ansiYellow", p.terminalAnsiYellow],
    ["terminal.ansiBlue", p.terminalAnsiBlue],
    ["terminal.ansiMagenta", p.terminalAnsiMagenta],
    ["terminal.ansiCyan", p.terminalAnsiCyan],
    ["terminal.ansiWhite", p.terminalAnsiWhite],
    ["terminal.ansiBrightBlack", p.terminalAnsiBrightBlack],
    ["terminal.ansiBrightRed", p.terminalAnsiBrightRed],
    ["terminal.ansiBrightGreen", p.terminalAnsiBrightGreen],
    ["terminal.ansiBrightYellow", p.terminalAnsiBrightYellow],
    ["terminal.ansiBrightBlue", p.terminalAnsiBrightBlue],
    ["terminal.ansiBrightMagenta", p.terminalAnsiBrightMagenta],
    ["terminal.ansiBrightCyan", p.terminalAnsiBrightCyan],
    ["terminal.ansiBrightWhite", p.terminalAnsiBrightWhite],
    ["terminal.tab.activeBorder", p.accent],
    ["terminalCommandDecoration.defaultBackground", p.terminalCommandDefault],
    ["terminalCommandDecoration.successBackground", p.terminalCommandSuccess],
    ["terminalCommandDecoration.errorBackground", p.terminalCommandError],
    ["gitDecoration.addedResourceForeground", p.accent2],
    ["gitDecoration.modifiedResourceForeground", p.accent],
    ["gitDecoration.deletedResourceForeground", p.accentMuted],
    ["gitDecoration.renamedResourceForeground", p.type],
    ["gitDecoration.untrackedResourceForeground", p.accent2Bright],
    ["gitDecoration.ignoredResourceForeground", p.muted],
    ["gitDecoration.stageModifiedResourceForeground", p.warning],
    ["gitDecoration.stageDeletedResourceForeground", p.accent],
    ["minimap.findMatchHighlight", p.findMatchBorder],
    ["minimap.selectionHighlight", p.accent],
    ["minimap.selectionOccurrenceHighlight", p.accent2Bright],
    ["minimap.errorHighlight", p.error],
    ["minimap.warningHighlight", p.warning],
    ["minimapGutter.modifiedBackground", p.accent],
    ["minimapGutter.addedBackground", p.accent2],
    ["minimapGutter.deletedBackground", p.accentMuted],
    ["diffEditor.insertedTextBackground", p.diffInserted],
    ["diffEditor.insertedTextBorder", "#00000000"],
    ["diffEditor.removedTextBackground", p.diffRemoved],
    ["diffEditor.removedTextBorder", "#00000000"],
    ["diffEditor.diagonalFill", p.panel],
    ["diffEditorGutter.insertedLineBackground", p.diffInserted],
    ["diffEditorGutter.removedLineBackground", p.diffRemoved],
    ["merge.currentHeaderBackground", p.mergeCurrentHeader],
    ["merge.currentContentBackground", p.mergeCurrentContent],
    ["merge.incomingHeaderBackground", p.mergeIncomingHeader],
    ["merge.incomingContentBackground", p.mergeIncomingContent],
    ["merge.commonHeaderBackground", p.mergeCommonHeader],
    ["merge.commonContentBackground", p.mergeCommonContent],
    ["editorPane.background", p.bg],
    ["problemsErrorIcon.foreground", p.error],
    ["problemsWarningIcon.foreground", p.warning],
    ["problemsInfoIcon.foreground", p.info],
    ["debugIcon.breakpointForeground", p.accent],
    ["debugIcon.breakpointCurrentStackframeForeground", p.warning],
    ["debugIcon.startForeground", p.accent2Bright],
    ["debugIcon.pauseForeground", p.warning],
    ["debugIcon.stopForeground", p.accentMuted],
    ["testing.iconErrored", p.error],
    ["testing.iconFailed", p.error],
    ["testing.iconPassed", p.accent2],
    ["testing.iconQueued", p.warning],
    ["testing.iconSkipped", p.muted],
    ["testing.peekBorder", p.border],
    ["testing.peekHeaderBackground", p.surface],
    ["notebook.cellBorderColor", p.border],
    ["notebook.cellHoverBackground", p.lineHighlight],
    ["notebook.cellInsertionIndicator", p.accent],
    ["notebook.selectedCellBorder", p.accent],
    ["notebook.selectedCellBackground", p.selectionHighlight],
    ["notebook.inactiveSelectedCellBorder", p.border],
    ["notebook.focusedCellBorder", p.accent],
    ["notebook.focusedEditorBorder", p.accent2],
    ["symbolIcon.arrayForeground", p.type],
    ["symbolIcon.booleanForeground", p.accent],
    ["symbolIcon.classForeground", p.type],
    ["symbolIcon.colorForeground", p.regex],
    ["symbolIcon.constantForeground", p.accent],
    ["symbolIcon.constructorForeground", p.accentStrong],
    ["symbolIcon.enumeratorForeground", p.accent2],
    ["symbolIcon.enumeratorMemberForeground", p.accent2Bright],
    ["symbolIcon.eventForeground", p.warning],
    ["symbolIcon.fieldForeground", p.secondaryText],
    ["symbolIcon.fileForeground", p.secondaryText],
    ["symbolIcon.folderForeground", p.secondaryText],
    ["symbolIcon.functionForeground", p.fg],
    ["symbolIcon.interfaceForeground", p.type],
    ["symbolIcon.keyForeground", p.accent],
    ["symbolIcon.keywordForeground", p.accent],
    ["symbolIcon.methodForeground", p.fg],
    ["symbolIcon.moduleForeground", p.type],
    ["symbolIcon.namespaceForeground", p.type],
    ["symbolIcon.nullForeground", p.muted],
    ["symbolIcon.numberForeground", p.accent],
    ["symbolIcon.objectForeground", p.fg],
    ["symbolIcon.operatorForeground", p.accent],
    ["symbolIcon.packageForeground", p.secondaryText],
    ["symbolIcon.propertyForeground", p.secondaryText],
    ["symbolIcon.referenceForeground", p.accent2Bright],
    ["symbolIcon.snippetForeground", p.regex],
    ["symbolIcon.stringForeground", p.accent2Bright],
    ["symbolIcon.structForeground", p.type],
    ["symbolIcon.textForeground", p.fg],
    ["symbolIcon.typeParameterForeground", p.type],
    ["symbolIcon.unitForeground", p.warning],
    ["symbolIcon.variableForeground", p.fg],
    ["chart.foreground", p.fg],
    ["chart.line", p.border],
    ["chart.red", p.error],
    ["chart.blue", p.type],
    ["chart.yellow", p.warning],
    ["chart.orange", p.accentStrong],
    ["chart.green", p.accent2],
    ["chart.purple", p.chartPurple],
    ["editorGhostText.foreground", p.ghostText],
  ]);

const tokenColors = (p) => [
  {
    scope: [
      "text.html.markdown",
      "text.html.markdown meta.paragraph",
      "meta.paragraph.markdown",
    ],
    settings: { foreground: p.prose },
  },
  {
    scope: ["meta.frontmatter", "meta.embedded.block.frontmatter"],
    settings: { foreground: p.frontmatterText },
  },
  {
    scope: [
      "entity.name.tag.yaml",
      "support.type.property-name.yaml",
      "meta.mapping.key.yaml",
      "punctuation.separator.key-value.yaml",
    ],
    settings: { foreground: p.frontmatterKey },
  },
  {
    scope: [
      "string.unquoted.yaml",
      "string.quoted.yaml",
      "meta.mapping.value.yaml",
    ],
    settings: { foreground: p.frontmatterValue },
  },
  {
    scope: [
      "support.type.property-name.json",
      "meta.structure.dictionary.json string.quoted.double.json",
    ],
    settings: { foreground: p.jsonKey },
  },
  {
    scope: [
      "meta.structure.dictionary.value.json string.quoted.double.json",
      "meta.structure.array.json string.quoted.double.json",
    ],
    settings: { foreground: p.jsonString },
  },
  {
    scope: [
      "punctuation.support.type.property-name.json",
      "punctuation.separator.dictionary.key-value.json",
      "punctuation.definition.string.begin.json",
      "punctuation.definition.string.end.json",
    ],
    settings: { foreground: p.jsonPunctuation },
  },
  {
    scope: ["constant.language.json", "constant.numeric.json"],
    settings: { foreground: p.jsonConstant },
  },
  {
    scope: ["comment", "punctuation.definition.comment"],
    settings: { foreground: p.comment, fontStyle: "italic" },
  },
  {
    scope: [
      "comment.block.documentation",
      "comment.block.documentation punctuation.definition.comment",
    ],
    settings: { foreground: p.commentDoc, fontStyle: "italic" },
  },
  {
    scope: [
      "keyword",
      "storage",
      "storage.type",
      "storage.modifier",
      "keyword.control",
      "keyword.operator.new",
      "keyword.operator.expression",
      "keyword.control.flow",
    ],
    settings: { foreground: p.keyword },
  },
  {
    scope: ["keyword.operator"],
    settings: { foreground: p.operator },
  },
  {
    scope: [
      "keyword.operator.assignment",
      "keyword.operator.comparison",
      "keyword.operator.logical",
      "keyword.operator.arithmetic",
    ],
    settings: { foreground: p.operatorStrong },
  },
  {
    scope: [
      "punctuation.accessor",
      "punctuation.separator.key-value",
      "punctuation.definition.tag",
      "punctuation.definition.template-expression",
    ],
    settings: { foreground: p.punctuation },
  },
  {
    scope: [
      "support.class.component",
      "entity.name.tag.localname.astro",
      "entity.name.tag.localname.jsx",
      "entity.name.tag.localname.tsx",
      "meta.jsx.children entity.name.tag",
      "meta.tag.custom.start entity.name.tag",
      "meta.tag.custom.end entity.name.tag",
    ],
    settings: { foreground: p.componentTag },
  },
  {
    scope: ["entity.name.tag", "meta.tag entity.name.tag"],
    settings: { foreground: p.tag },
  },
  {
    scope: [
      "entity.other.attribute-name",
      "entity.other.attribute-name.astro",
      "entity.other.attribute-name.jsx",
      "entity.other.attribute-name.tsx",
      "meta.tag.attributes entity.other.attribute-name",
      "support.type.property-name.css",
      "meta.property-list.css meta.property-name",
      "entity.other.attribute-name.class.css",
    ],
    settings: { foreground: p.attribute },
  },
  {
    scope: [
      "text.html.astro meta.tag string.quoted",
      "text.html.astro meta.tag string.quoted punctuation.definition.string",
      "meta.jsx string.quoted",
      "meta.jsx string.quoted punctuation.definition.string",
    ],
    settings: { foreground: p.attributeString },
  },
  {
    scope: [
      "text.html.astro meta.jsx.children",
      "text.html.astro meta.tag meta.embedded.expression",
      "meta.jsx.children",
    ],
    settings: { foreground: p.jsxText },
  },
  {
    scope: [
      "entity.name.tag.css",
      "entity.other.attribute-name.class.css",
      "entity.other.attribute-name.id.css",
      "meta.selector.css entity.other.attribute-name",
      "meta.selector.css",
    ],
    settings: { foreground: p.cssSelector },
  },
  {
    scope: [
      "support.type.property-name.css",
      "meta.property-name.css",
      "meta.property-list.css meta.property-name",
      "variable.css",
      "variable.argument.css",
    ],
    settings: { foreground: p.cssProperty },
  },
  {
    scope: [
      "variable.other.custom-property.css",
      "support.type.custom-property.name.css",
      "meta.property-value.css variable.other.custom-property.css",
    ],
    settings: { foreground: p.cssCustomProperty },
  },
  {
    scope: [
      "support.function.css",
      "support.function.misc.css",
      "meta.function-call.css",
      "entity.name.function.css",
    ],
    settings: { foreground: p.cssFunction },
  },
  {
    scope: [
      "constant.numeric.css",
      "keyword.other.unit.css",
      "constant.other.color.rgb-value.css",
      "support.constant.color",
    ],
    settings: { foreground: p.cssNumber },
  },
  {
    scope: [
      "support.constant.property-value.css",
      "constant.other.color.css",
      "keyword.other.important.css",
    ],
    settings: { foreground: p.cssValue },
  },
  {
    scope: [
      "punctuation.definition.entity.css",
      "punctuation.separator.list.comma.css",
      "punctuation.section.property-list.css",
      "punctuation.terminator.rule.css",
    ],
    settings: { foreground: p.cssPunctuation },
  },
  {
    scope: [
      "string",
      "string.quoted",
      "string.template",
      "markup.inline.raw",
      "markup.fenced_code.block.markdown",
    ],
    settings: { foreground: p.string },
  },
  {
    scope: [
      "meta.import string.quoted",
      "meta.import string.quoted punctuation.definition.string",
    ],
    settings: { foreground: p.importPath },
  },
  {
    scope: [
      "source.js meta.import variable.other.readwrite",
      "source.js meta.import variable.other.readwrite.alias",
      "source.js meta.import entity.name.function",
      "source.js meta.import entity.name.type",
      "source.js meta.import variable.other.constant",
      "source.js meta.import support.variable",
    ],
    settings: { foreground: p.jsImported },
  },
  {
    scope: [
      "source.js support.class.builtin",
      "source.js support.type.object",
      "source.js variable.language.import-meta",
      "source.js variable.language",
    ],
    settings: { foreground: p.jsBuiltin },
  },
  {
    scope: [
      "source.js entity.name.function",
      "source.js support.function",
      "source.js variable.function",
      "source.js meta.function-call entity.name.function",
      "source.js meta.function-call support.function",
    ],
    settings: { foreground: p.jsFunction },
  },
  {
    scope: [
      "source.js variable.other.property",
      "source.js support.variable.property",
      "source.js meta.property.object",
      "source.js meta.member.access variable.other.property",
    ],
    settings: { foreground: p.jsProperty },
  },
  {
    scope: [
      "source.js variable.other.constant",
      "source.js variable.other.readwrite",
      "source.js meta.definition.variable variable.other.readwrite",
    ],
    settings: { foreground: p.jsVariable },
  },
  {
    scope: [
      "string.regexp",
      "constant.other.character-class.regexp",
      "keyword.other.quantifier.regexp",
    ],
    settings: { foreground: p.regex },
  },
  {
    scope: [
      "constant.character.escape",
      "constant.other.placeholder",
      "punctuation.section.embedded",
    ],
    settings: { foreground: p.escape },
  },
  {
    scope: [
      "constant.numeric",
      "constant.language.boolean",
      "constant.language.null",
      "constant.language.undefined",
      "constant.language.nan",
      "constant.character",
    ],
    settings: { foreground: p.number },
  },
  {
    scope: [
      "constant.language",
      "support.constant",
      "support.variable.magic",
      "variable.language",
      "variable.language.this",
      "variable.language.self",
      "variable.language.super",
    ],
    settings: { foreground: p.builtin },
  },
  {
    scope: [
      "entity.name.type",
      "support.type",
      "support.class",
      "entity.name.namespace",
      "entity.name.module",
      "meta.type.annotation",
      "storage.type.annotation",
    ],
    settings: { foreground: p.type },
  },
  {
    scope: [
      "entity.name.class",
      "entity.name.struct",
      "entity.name.interface",
      "entity.name.enum",
      "support.class.component",
    ],
    settings: { foreground: p.typeBright },
  },
  {
    scope: [
      "entity.name.function",
      "support.function",
      "meta.function-call",
      "variable.function",
      "entity.name.method",
      "support.function.any-method",
    ],
    settings: { foreground: p.function },
  },
  {
    scope: [
      "meta.method-call",
      "meta.member.access",
      "variable.other.property",
      "variable.other.object.property",
      "support.variable.property",
    ],
    settings: { foreground: p.property },
  },
  {
    scope: [
      "meta.import variable.other.readwrite",
      "meta.import entity.name.type",
      "meta.import entity.name.function",
      "variable.other.readwrite.alias",
    ],
    settings: { foreground: p.imported },
  },
  {
    scope: [
      "entity.name.function.decorator",
      "entity.name.function.preprocessor",
      "meta.annotation",
      "punctuation.definition.annotation",
    ],
    settings: { foreground: p.decorator },
  },
  {
    scope: ["variable", "meta.definition.variable", "support.variable"],
    settings: { foreground: p.variable },
  },
  {
    scope: ["variable.parameter", "meta.function.parameters"],
    settings: { foreground: p.parameter },
  },
  {
    scope: [
      "meta.object-literal.key",
      "meta.object-literal.key variable",
      "meta.object-literal.key variable.other",
      "meta.object-literal.key variable.other.readwrite",
      "meta.object-literal.key entity.name",
      "meta.object-literal.key string",
      "meta.property.object string.quoted",
      "meta.structure.dictionary.key string.quoted",
      "source.js meta.object-literal.key",
      "source.ts meta.object-literal.key",
      "source.tsx meta.object-literal.key",
      "source.tsx meta.object.member.tsx meta.object-literal.key.tsx",
      "source.astro meta.object-literal.key",
      "source.astro meta.object-literal.key.tsx",
      "source.astro meta.object.member.tsx meta.object-literal.key.tsx",
      "source.astro meta.embedded.expression.astro meta.object-literal.key",
      "source.astro meta.embedded.expression.astro meta.object-literal.key.tsx",
      "source.astro meta.embedded.expression.astro meta.object.member.tsx meta.object-literal.key.tsx",
      "source.astro meta.embedded.expression.astro source.tsx meta.object-literal.key",
      "source.astro meta.embedded.expression.astro source.tsx meta.object-literal.key.tsx",
      "source.astro meta.embedded.expression.astro source.tsx meta.objectliteral.tsx meta.object.member.tsx meta.object-literal.key.tsx",
    ],
    settings: { foreground: p.objectKey },
  },
  {
    scope: ["entity.name.label", "entity.name.section", "entity.name.filename"],
    settings: { foreground: p.warning },
  },
  {
    scope: [
      "punctuation",
      "meta.brace",
      "meta.delimiter",
      "meta.separator",
      "punctuation.section.embedded.begin.astro",
      "punctuation.section.embedded.end.astro",
    ],
    settings: { foreground: p.punctuation },
  },
  {
    scope: [
      "source.astro support.class.component.astro",
      "source.astro meta.tag.start.astro support.class.component.astro",
      "source.astro meta.tag.end.astro support.class.component.astro",
    ],
    settings: { foreground: p.componentTag },
  },
  {
    scope: [
      "source.astro entity.name.tag.astro",
      "source.astro meta.tag.custom.astro entity.name.tag.astro",
      "source.astro meta.tag.start.astro entity.name.tag.astro",
      "source.astro meta.tag.end.astro entity.name.tag.astro",
    ],
    settings: { foreground: p.tag },
  },
  {
    scope: [
      "source.astro entity.other.attribute-name.astro",
      "source.astro meta.attribute entity.other.attribute-name.astro",
      "source.astro meta.tag.start.astro entity.other.attribute-name.astro",
    ],
    settings: { foreground: p.attribute },
  },
  {
    scope: [
      "source.astro string.quoted.astro",
      "source.astro string.unquoted.astro",
      "source.astro string.template.astro",
      "source.astro punctuation.definition.string.begin.astro",
      "source.astro punctuation.definition.string.end.astro",
    ],
    settings: { foreground: p.attributeString },
  },
  {
    scope: [
      "source.astro punctuation.definition.tag.begin.astro",
      "source.astro punctuation.definition.tag.end.astro",
      "source.astro punctuation.separator.key-value.astro",
      "source.astro punctuation.section.embedded.begin.astro",
      "source.astro punctuation.section.embedded.end.astro",
    ],
    settings: { foreground: p.punctuation },
  },
  {
    scope: [
      "invalid",
      "invalid.illegal",
      "invalid.illegal.unclosed-string",
      "invalid.illegal.unclosed-string.json",
      "string.invalid",
      "string.invalid.illegal",
      "string.quoted.double.invalid",
      "string.quoted.double.invalid.illegal",
      "string.quoted.double.json.invalid.illegal",
    ],
    settings: {
      foreground: p.error,
      background: p.invalidBg,
      fontStyle: "underline",
    },
  },
  {
    scope: ["invalid.deprecated"],
    settings: { foreground: p.warning, fontStyle: "underline" },
  },
  {
    scope: ["markup.heading", "markup.heading punctuation.definition.heading"],
    settings: { foreground: p.markupHeading, fontStyle: "bold" },
  },
  {
    scope: ["markup.bold"],
    settings: { foreground: p.fg, fontStyle: "bold" },
  },
  {
    scope: ["markup.italic"],
    settings: { foreground: p.markupItalic, fontStyle: "italic" },
  },
  {
    scope: ["markup.link", "string.other.link"],
    settings: { foreground: p.markupLink, fontStyle: "underline" },
  },
  {
    scope: ["markup.quote", "punctuation.definition.blockquote"],
    settings: { foreground: p.markupQuote, fontStyle: "italic" },
  },
  {
    scope: ["markup.list", "punctuation.definition.list.begin.markdown"],
    settings: { foreground: p.accentStrong },
  },
  {
    scope: ["markup.inserted"],
    settings: { foreground: p.accent2Bright },
  },
  {
    scope: ["markup.deleted"],
    settings: { foreground: p.accentMuted },
  },
  {
    scope: ["markup.changed"],
    settings: { foreground: p.warning },
  },
];

const semanticTokenColors = (p) => ({
  namespace: p.type,
  class: p.typeBright,
  interface: p.typeBright,
  type: p.type,
  enum: p.typeBright,
  typeParameter: p.type,
  parameter: p.parameter,
  variable: p.variable,
  "variable.readonly": p.accent2Bright,
  "variable.defaultLibrary": p.builtin,
  property: p.property,
  "property.declaration": p.objectKey,
  "property.readonly": p.propertyReadonly,
  "property.readonly.declaration": p.objectKeyReadonly,
  function: p.function,
  "function.defaultLibrary": p.builtin,
  method: p.method,
  "method.defaultLibrary": p.builtin,
  macro: p.decorator,
  decorator: p.decorator,
  keyword: p.keyword,
  operator: p.operatorStrong,
  string: p.string,
  regexp: p.regex,
  number: p.number,
  boolean: p.number,
  enumMember: p.accent2Bright,
  event: p.warning,
  label: p.warning,
  comment: {
    foreground: p.comment,
    italic: true,
  },
});

const theme = (name, type, p) => ({
  $schema: "vscode://schemas/color-theme",
  name,
  type,
  semanticHighlighting: true,
  colors: sharedColors(p),
  tokenColors: tokenColors(p),
  semanticTokenColors: semanticTokenColors(p),
});

const light = {
  bg: "#FFFFFF",
  surface: "#FCFAF6",
  panelBg: "#FCFAF6",
  panel: "#FFFDF9",
  chrome: "#FFFFFF",
  fg: "#111820",
  secondaryText: "#2B3A44",
  muted: "#53626D",
  comment: "#465762",
  commentDoc: "#536570",
  border: "#E3D8CA",
  subtleBorder: "#F0EAE2",
  lineNumber: "#687780",
  cursor: "#0F1113",
  cursorCharacterForeground: "#F3EFE7",
  accent: "#A83D16",
  accentStrong: "#5F210D",
  accentMuted: "#8F3B21",
  error: "#C03030",
  errorFg: "#FFFFFF",
  invalidBg: "#C0303012",
  statusBarErrorBg: "#C03030",
  bracketAlt: "#743762",
  accent2: "#184C37",
  accent2Bright: "#0B784F",
  accent2Fill: "#184C37",
  accent2FillHover: "#006F49",
  keyword: "#8B3D18",
  decorator: "#A83D16",
  escape: "#A83D16",
  tag: "#006C96",
  componentTag: "#6B4D20",
  attribute: "#99621B",
  attributeString: "#0B784F",
  jsxText: "#111820",
  type: "#005982",
  typeBright: "#00688E",
  string: "#0B784F",
  regex: "#AD4B22",
  number: "#AD4B22",
  builtin: "#6B4D20",
  imported: "#99621B",
  importPath: "#0B784F",
  jsImported: "#99621B",
  jsBuiltin: "#6B4D20",
  jsFunction: "#00729B",
  jsProperty: "#6B5A44",
  objectKey: "#99621B",
  objectKeyReadonly: "#5F4A2D",
  jsVariable: "#111820",
  prose: "#20262C",
  frontmatterText: "#2B3A44",
  frontmatterKey: "#99621B",
  frontmatterValue: "#0B784F",
  jsonKey: "#99621B",
  jsonString: "#0B784F",
  jsonPunctuation: "#40515B",
  jsonConstant: "#AD4B22",
  cssSelector: "#6B4D20",
  cssProperty: "#006C96",
  cssCustomProperty: "#0B784F",
  cssFunction: "#00729B",
  cssNumber: "#AD4B22",
  cssValue: "#0B784F",
  cssPunctuation: "#40515B",
  markupHeading: "#4F3E28",
  markupItalic: "#0B784F",
  markupLink: "#006C96",
  markupQuote: "#2B3A44",
  function: "#00729B",
  method: "#00729B",
  variable: "#111820",
  property: "#6B5A44",
  propertyReadonly: "#005982",
  parameter: "#2B3A44",
  punctuation: "#40515B",
  operator: "#4E6170",
  operatorStrong: "#8B3D18",
  ghostText: "#B0B8C0",
  chartPurple: "#7B5EA7",
  selection: "#B5633C42",
  inactiveSelection: "#B5633C2A",
  selectionHighlight: "#184C372E",
  selectionBorder: "#184C3770",
  wordHighlight: "#184C3728",
  wordHighlightBorder: "#184C3775",
  wordHighlightStrong: "#B5633C28",
  wordHighlightStrongBorder: "#B5633C75",
  findMatch: "#184C3755",
  findMatchHighlight: "#184C3730",
  findMatchBorder: "#184C37B0",
  findRange: "#184C371E",
  lineHighlight: "#F7F9FB",
  rangeHighlight: "#F2F5F7",
  fold: "#184C3718",
  listActive: "#B5633C5C",
  listFocus: "#B5633C4A",
  listHover: "#FFFDF9",
  listInactive: "#B5633C22",
  drop: "#B5633C34",
  inlayBg: "#F4F1EB",
  inlayFg: "#465762",
  inlayTypeBg: "#184C371E",
  inlayTypeFg: "#1D4D39",
  inlayParamBg: "#B5633C22",
  inlayParamFg: "#7A3D20",
  diffInserted: "#184C3720",
  diffRemoved: "#B5633C1E",
  mergeCurrentHeader: "#184C3734",
  mergeCurrentContent: "#184C371E",
  mergeIncomingHeader: "#B5633C34",
  mergeIncomingContent: "#B5633C1E",
  mergeCommonHeader: "#E3D8CA",
  mergeCommonContent: "#FCFAF6",
  warning: "#77501F",
  info: "#0D5E7C",
  badgeFg: "#F3EFE7",
  buttonBg: "#6F371F",
  buttonHoverBg: "#5B2C18",
  buttonFg: "#F3EFE7",
  badgeLight: "#FFFFFF",
  selectedFg: "#1E2328",
  terminalAnsiBlack: "#1E2328",
  terminalAnsiRed: "#8E2F0E",
  terminalAnsiGreen: "#0B784F",
  terminalAnsiYellow: "#795E26",
  terminalAnsiBlue: "#00729B",
  terminalAnsiMagenta: "#743762",
  terminalAnsiCyan: "#007676",
  terminalAnsiWhite: "#40505A",
  terminalAnsiBrightBlack: "#596874",
  terminalAnsiBrightRed: "#A83D16",
  terminalAnsiBrightGreen: "#0B784F",
  terminalAnsiBrightYellow: "#6B5420",
  terminalAnsiBrightBlue: "#005BA1",
  terminalAnsiBrightMagenta: "#743762",
  terminalAnsiBrightCyan: "#007676",
  terminalAnsiBrightWhite: "#1E2328",
  terminalCommandDefault: "#53626D",
  terminalCommandSuccess: "#184C37",
  terminalCommandError: "#C03030",
};

const dark = {
  bg: "#0F1113",
  surface: "#1A1D20",
  panelBg: "#1A1D20",
  panel: "#252A2E",
  chrome: "#0F1113",
  fg: "#F3EFE7",
  secondaryText: "#C4CDD4",
  muted: "#8E9CA6",
  comment: "#A19682",
  commentDoc: "#ADA28E",
  border: "#2D3339",
  subtleBorder: "#252A2E",
  lineNumber: "#7C8993",
  cursor: "#F3EFE7",
  cursorCharacterForeground: "#0F1113",
  accent: "#CC7A52",
  accentStrong: "#D98B66",
  accentMuted: "#D47764",
  error: "#E05252",
  errorFg: "#FFFFFF",
  invalidBg: "#E0525218",
  statusBarErrorBg: "#C04040",
  bracketAlt: "#A88878",
  accent2: "#5F876F",
  accent2Bright: "#A8D2B0",
  accent2Fill: "#4A6B5A",
  accent2FillHover: "#527760",
  keyword: "#CC7A52",
  decorator: "#D98B66",
  escape: "#D98B66",
  tag: "#B8C5C8",
  componentTag: "#E5C8A0",
  attribute: "#D5B080",
  attributeString: "#A8D2B0",
  jsxText: "#F3EFE7",
  type: "#B0C0C4",
  typeBright: "#D5DCDD",
  string: "#A8D2B0",
  regex: "#D5B080",
  number: "#E2A595",
  builtin: "#E5C8A0",
  imported: "#D5B080",
  importPath: "#A8D2B0",
  jsImported: "#D5B080",
  jsBuiltin: "#D5DCDD",
  jsFunction: "#C0CFCF",
  jsProperty: "#D8CAB0",
  objectKey: "#D5B080",
  objectKeyReadonly: "#B5926A",
  jsVariable: "#F3EFE7",
  prose: "#F3EFE7",
  frontmatterText: "#DFDAC8",
  frontmatterKey: "#D5B080",
  frontmatterValue: "#A8D2B0",
  jsonKey: "#D5B080",
  jsonString: "#A8D2B0",
  jsonPunctuation: "#B5B5A8",
  jsonConstant: "#E2A595",
  cssSelector: "#E5C8A0",
  cssProperty: "#B0C0C4",
  cssCustomProperty: "#A8D2B0",
  cssFunction: "#C0CFCF",
  cssNumber: "#E2A595",
  cssValue: "#A8D2B0",
  cssPunctuation: "#B5B5A8",
  markupHeading: "#E5C8A0",
  markupItalic: "#A8D2B0",
  markupLink: "#B8C5C8",
  markupQuote: "#DFDAC8",
  function: "#C0CFCF",
  method: "#C0CFCF",
  variable: "#F3EFE7",
  property: "#D8CAB0",
  propertyReadonly: "#D5DCDD",
  parameter: "#DFDAC8",
  punctuation: "#B5B5A8",
  operator: "#959890",
  operatorStrong: "#CC7A52",
  ghostText: "#4A4A42",
  chartPurple: "#A88878",
  selection: "#CC7A523D",
  inactiveSelection: "#CC7A5226",
  selectionHighlight: "#4A6B5A26",
  selectionBorder: "#4A6B5A55",
  wordHighlight: "#4A6B5A22",
  wordHighlightBorder: "#4A6B5A66",
  wordHighlightStrong: "#CC7A5224",
  wordHighlightStrongBorder: "#CC7A5266",
  findMatch: "#4A6B5A55",
  findMatchHighlight: "#4A6B5A28",
  findMatchBorder: "#8FB19F99",
  findRange: "#4A6B5A16",
  lineHighlight: "#1E1814",
  rangeHighlight: "#1E1814",
  fold: "#CC7A5210",
  listActive: "#CC7A5250",
  listFocus: "#CC7A5242",
  listHover: "#2A2520",
  listInactive: "#CC7A5216",
  drop: "#CC7A5228",
  inlayBg: "#1E1814",
  inlayFg: "#B8B0A0",
  inlayTypeBg: "#4A6B5A16",
  inlayTypeFg: "#C7D0D2",
  inlayParamBg: "#CC7A5216",
  inlayParamFg: "#DCA088",
  diffInserted: "#4A6B5A22",
  diffRemoved: "#CC7A521C",
  mergeCurrentHeader: "#4A6B5A30",
  mergeCurrentContent: "#4A6B5A1A",
  mergeIncomingHeader: "#CC7A5230",
  mergeIncomingContent: "#CC7A521A",
  mergeCommonHeader: "#2D3339",
  mergeCommonContent: "#252A2E",
  warning: "#D4B998",
  info: "#9BBFD4",
  badgeFg: "#0F1113",
  buttonBg: "#CC7A52",
  buttonHoverBg: "#CC7A52",
  buttonFg: "#0F1113",
  badgeLight: "#FFF8EC",
  selectedFg: "#FFF8EC",
  terminalAnsiBlack: "#707C86",
  terminalAnsiRed: "#CC7A52",
  terminalAnsiGreen: "#8CCAA0",
  terminalAnsiYellow: "#C49E6E",
  terminalAnsiBlue: "#B0C5CD",
  terminalAnsiMagenta: "#A88878",
  terminalAnsiCyan: "#A4BBC6",
  terminalAnsiWhite: "#F3EFE7",
  terminalAnsiBrightBlack: "#BFC0B0",
  terminalAnsiBrightRed: "#CC7A52",
  terminalAnsiBrightGreen: "#A8C2B2",
  terminalAnsiBrightYellow: "#D8B98E",
  terminalAnsiBrightBlue: "#C2D2DA",
  terminalAnsiBrightMagenta: "#B89A92",
  terminalAnsiBrightCyan: "#C2D2DA",
  terminalAnsiBrightWhite: "#FFF8EC",
  terminalCommandDefault: "#69737B",
  terminalCommandSuccess: "#BDD2C2",
  terminalCommandError: "#E05252",
};

const outputs = [
  {
    path: resolve(themesDir, "stationery-light.json"),
    data: theme("Stationery Light", "light", light),
  },
  {
    path: resolve(themesDir, "stationery-dark.json"),
    data: theme("Stationery Dark", "dark", dark),
  },
];

const lightKeys = new Set(Object.keys(light));
const darkKeys = new Set(Object.keys(dark));
const onlyLight = [...lightKeys].filter((k) => !darkKeys.has(k));
const onlyDark = [...darkKeys].filter((k) => !lightKeys.has(k));
if (onlyLight.length || onlyDark.length) {
  throw new Error(
    `Palette key drift — light only: [${onlyLight.join(", ")}]; dark only: [${onlyDark.join(", ")}]`,
  );
}

const HEX = /^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$/;
for (const [name, palette] of Object.entries({ light, dark })) {
  for (const [key, value] of Object.entries(palette)) {
    if (
      typeof value === "string" &&
      value.startsWith("#") &&
      !HEX.test(value)
    ) {
      throw new Error(
        `${name}.${key} = "${value}" is not a valid 6/8-digit hex color`,
      );
    }
  }
}

mkdirSync(themesDir, { recursive: true });

for (const output of outputs) {
  const json = JSON.stringify(output.data, null, 2);
  if (json.includes('"undefined"')) {
    throw new Error(
      `${output.path} contains "undefined" values — a palette key referenced by the transformers is missing`,
    );
  }
  writeFileSync(output.path, `${json}\n`);
}
